### PR TITLE
Meka works fine now

### PR DESCRIPTION
**Pull request by jbaudisch**
With this version, the Meka is "finished".
I fixed the way how the armature is built again because there was an issue with the bone-orientation.

Pepper has still scaling problems which i don't understand for now.

### CODE REVIEW

**Comment by severin-lemaignan** [comment]
Great! Btw, when I run `meka_testing.py`, tenth of (spurious?) cameras are created as well. It is not immediately clear who create them... do you know about it?

**Comment by jbaudisch** [comment]
They were created by the collada/stl files.

**Comment by severin-lemaignan** [comment]
I've fixed the issue with Pepper (due to... an outdated URDF file (!!) + scaling being applied twice.

Looks good now!
pepper

**Comment by severin-lemaignan** [comment]
Next step, cleaning up the commits, finishing the integration with the rest of MORSE (-> if you run `morse edit meka_testing.py` and then press `P` to start the simulation, MORSE exits immediately as the URDF builder is not yet properly integrated). I'm going to create a PR on the main MORSE repo, where we can finish off these bits.

**Comment by jbaudisch** [comment]
> outdated URDF file

Ah that's what I thought.. but good it works fine now!

**Comment by jbaudisch** [comment]
@severin-lemaignan What do you mean with "cleaning up the commits"?

**Comment by severin-lemaignan** [comment]
Merging related commits together, to have a shorter, cleaner history. I've just done that on my branch.

**Comment by jbaudisch** [comment]
Do you know why the Game-Mode (press `P`) "destroys" the Robot?
r2d2

**Comment by severin-lemaignan** [comment]
Hum... that's a good point... I only tested the 'run' mode with the Meka robot, and even though it looked kind of weird, I thought it was just a rendering issue. I did not realize that the robot was actually 'exploded'. I've no immediate idea *why* it does that... it would require a bit of investigation...

**Comment by severin-lemaignan** [comment]
Usually, this kind of issue is related to some scaling not being applied, but even after manually applying the scaling to the robot, I still get the exploded version when pressing P...

**Comment by severin-lemaignan** [comment]
If you delete all the bones of the robot, it does not 'explode' anymore. So the issue is linked to 'something' being applied by the bones to their objects location when starting the game engine.

**Comment by jbaudisch** [comment]
It looks like the bone-locations are doubled in 'run' mode.

**Comment by jbaudisch** [comment]
If we remove `armature.data.bones[joint.name].use_relative_parent = True` this, the edit-mode-robot looks like the run-mode-robot (exploded)

**Comment by jbaudisch** [comment]
I'm close to the solution i think.

**Comment by jbaudisch** [comment]
If we remove also these to lines of code:
`           v.location = armature.matrix_world * self.posebone.matrix * self.posebone.location
            v.rotation_quaternion = v.rotation_quaternion * joint.rot`
The robot looks better with this, but the origins of the meshes are located wrong (append to bone's tail not to bone's head).

**Comment by jbaudisch** [comment]
r2d2

**Comment by severin-lemaignan** [comment]
hum... I've also just realised that the joint constraint axis (at least for R2D2 'shoulders') is not correct (X instead of Y)...

**Comment by jbaudisch** [comment]
That's right, but that's how the urdf describe it, so it's okay, isn't it?
The real "r2d2.urdf" has fixed joints (no movement), i modified it for testing.

**Comment by jbaudisch** [comment]
That's right, but that's how the urdf describe it, so it's okay, isn't it?
The real "r2d2.urdf" has fixed joints (no movement), i modified it for testing.

**Comment by jbaudisch** [comment]
That's right, but that's how the urdf describe it, so it's okay, isn't it?
The real "r2d2.urdf" has fixed joints (no movement), i modified it for testing.

**Comment by severin-lemaignan** [comment]
I see, ok, no worries then (even though, it might be worth modifying it again to have the right axis, otherwise people will wonder whether we have a bug...)

**Comment by jbaudisch** [comment]
Ideas to set the mesh-origin from bone's tail to bone's head nicely?

**Comment by jbaudisch** [comment]
So the thing is (v is one visual):
`v.parent = armature`
`v.parent_bone = joint.name`
`v.parent_type = "BONE"`

This sets the v.location to bone's tail location but what we need is to set it to the bone's head.

**Comment by jbaudisch** [comment]
Okay, new approach:
`armature.data.bones[joint.name].use_relative_parent = True` 

Ignored in run-mode? Workaround?

**Comment by jbaudisch** [comment]
@severin-lemaignan 
Hey!
I got a new version on git. With that version there is no 'explode' anymore.

Only issue:
I don't know how to rotate the link-visual-geometry correctly.
I thought it would be like that:
`v.rotation_quaternion = link.rot`
but that's not the solution cause the meka-base is rotated wrong.
base

**So why is that?**
The object is already rotated correctly in the Collada/STL file. With the line of code above, we give it the wrong rotation than. But how can i find out, if the rotation is already correct?

**Pull request merged**
