### PR TITLE
urdf

### PR DESCRIPTION
**Pull request by jbaudisch**
@severin-lemaignan I got good and bad news here.

**Bad**: Seems like there were an update for urdf-file (sometime) which allows to have multiple visuals in one link. [Source](http://wiki.ros.org/urdf/XML/link) The URDF-Parser (urdf_parser_py.urdf) seems to be outdated. (Meka has one link with two visuals => only one is returned by the Parser)
one_visual

**Good**: I fixed the translation issues. Scaling is correct on Meka now, Pepper is still incorrect somehow (but now very tiny, not large). I think the trigger for that is the scale property: scale="0.1 0.1 0.1"

### CODE REVIEW

**Comment by severin-lemaignan** [comment]
meka

The Meka robot, from its URDF file. Moving joints in 'pose mode' seems to do what is expected, including the right joint limits.

**Comment by jbaudisch** [comment]
thumbs
On a closer look i saw some issues with the thumbs of Meka (position and rotation), still don't know why.

**Comment by jbaudisch** [comment]
@severin-lemaignan 

As already explained here, there were some trouble with the thumbs of the Meka robot.
I understood this issue now and want to fix it.

**The issue:**

We set the location of a bone's head like that:
`self.editbone.head = self.rot * self.xyz + parent.editbone.head`
but that's not the right way, because the xyz-location is not affected by the rotation. The procedure is like:

- Set joint's position (xyz)
- Set joint's orientation (rpy)

After that, the childrens have to use the orientation of the parent.

I have changed it in my [branch](https://github.com/jbaudisch/morse/tree/urdf) already.

But now I got the problem, that the axis are not correct anymore because the local axis are changed (e.g. X is Z). This breaks the constraints which where set in the configure_joint method.

Is there a way to 'reset' the axis?

**Comment by severin-lemaignan** [comment]
Doesn't [constraint's `owner_space` property](https://docs.blender.org/api/2.78a/bpy.types.Constraint.html#bpy.types.Constraint.owner_space) solve the issue?

**Pull request merged**
