### PR TITLE
New version of armature-creation

### PR DESCRIPTION
**Pull request by jbaudisch**
I implemented a new idea where the bones are represented as joints, all created bones have a length near zero (i called the variable epsilon), so they can be handled as points no matter what direction they have. This should also fix the zero-length problem cause there is no zero-length anymore.

The R2D2 look pretty solid now. On the Meka Robot we have still some problems with the visual components (scaling, positioning) (armature looks correct)

### CODE REVIEW

**Comment by severin-lemaignan** [comment]
Sounds good! I'll have a look hopefully tomorrow.

**Comment by severin-lemaignan** [comment]
@jbaudisch [R2D2](http://wiki.ros.org/urdf/Tutorials/Building%20a%20Visual%20Robot%20Model%20with%20URDF%20from%20Scratch) looks great! Well done!

r2d2

**Comment by severin-lemaignan** [comment]
Here's Pepper, using the (untouched) official URDF file:

pepper

We still have a major scaling issue (the meshes are several order of magiutude larger than the bones) + wrong transformation for the arms.

I'm going to add this model as one of the test case.

**Comment by severin-lemaignan** [comment]
@jbaudisch I've added the Pepper URDF model + all the Collada/STL files. That makes for a good, complex test case if you want to look at it.

**Comment by jbaudisch** [comment]
@severin-lemaignan Thank you! I'll have a look on Pepper later on.
Yes, there are still problems with the scaling and transformation of imported Collada/STL Objects.
I'll have a look on that too. For now i'm working on some joint-configurations like axis and limits.

**Pull request merged**
